theme:  jekyll-theme-slate
title: snake
link: https://github.com/dwimmer1/2223_4AHITN_Snake_sbegic_lnagler1_mrester_dwimmer/edit/main/_config.yml
description: Bookmark this to keep an eye on my project updates!
